Repository Skill-Forge-Project/skill_forge_auth, pull requests merged in 2025-06, with the labels that each got.

#1 Add lint workflow reference
  .github/workflows/run-lint-check.yml
Labels: documentation

#4 Potential fix for code scanning alert no. 1: Information exposure through an exception
  routes.py
Labels: bug

#6 ISSUE #308 Fix broken registration flow and ensure login redirection upon signup
  routes.py
Labels: bug

#7 Potential fix for code scanning alert no. 3: Workflow does not contain permissions
  .github/workflows/run-lint-check.yml
Labels: bug

#8 ISSUE #5: Add refresh token functionality - Backend Enhancement
  routes.py
  services.py
Labels: enhancement
